AWSTemplateFormatVersion: '2010-09-09'
Description: 'Dog Voting App - Serverless deployment with Lambda, DynamoDB, and S3'

Parameters:
  BucketName:
    Type: String
    Default: dog-voting-app-bucket
    Description: Name for the S3 bucket (must anapp.js:277 
            
            
           POST https://dxc81zd25i.execute-api.us-east-1.amazonaws.com/api/vote/efd14817-aa16-4da8-93d6-931f683b04ae 403 (Forbidden)
voteForDog @ app.js:277
swipeRight @ app.js:191
handleEnd @ app.js:111Understand this error
app.js:285 Vote response data: {message: 'Forbidden'}
app.js:276 Voting for dog/cat ID: 541eac00-abfd-4f4c-bc06-554897f4c4a4
app.js:277 
            
            
           POST https://dxc81zd25i.execute-api.us-east-1.amazonaws.com/api/vote/541eac00-abfd-4f4c-bc06-554897f4c4a4 403 (Forbidden)
voteForDog @ app.js:277
swipeRight @ app.js:191
handleEnd @ app.js:111Understand this error
app.js:285 Vote response data: {message: 'Forbidden'}
10app.js:84 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at HTMLDocument.handleMove (app.js:84:43)
handleMove @ app.js:84Understand this error
app.js:276 Voting for dog/cat ID: 34cd7bb2-a24e-4df5-9915-0cdd389af457
app.js:277 
            
            
           POST https://dxc81zd25i.execute-api.us-east-1.amazonaws.com/api/vote/34cd7bb2-a24e-4df5-9915-0cdd389af457 403 (Forbidden)
voteForDog @ app.js:277
swipeRight @ app.js:191
handleEnd @ app.js:111Understand this error
app.js:285 Vote response data: {message: 'Forbidden'}be globally unique)
  
  LambdaFunctionName:
    Type: String
    Default: dog-voting-app
    Description: Name for the Lambda function

Resources:
  # S3 Bucket for storing images
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketName}-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, POST, DELETE, HEAD]
            AllowedOrigins: ['*']
            MaxAge: 3000

  # S3 Bucket Policy (separate from bucket to avoid circular dependency)
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: S3Bucket
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"

  # DynamoDB Table for storing votes and metadata
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${LambdaFunctionName}-table"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  # IAM Role for Lambda function
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${LambdaFunctionName}-execution-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub "${S3Bucket.Arn}/*"
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt DynamoDBTable.Arn

  # Lambda Function
  LambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaExecutionRole
      - S3Bucket
      - DynamoDBTable
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Runtime: python3.12
      Handler: lambda_app.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def handler(event, context):
              return {
                  'statusCode': 200,
                  'body': 'Placeholder - will be updated by deploy script'
              }
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3Bucket
          DYNAMODB_TABLE: !Ref DynamoDBTable
          REGION: !Ref AWS::Region
      Timeout: 30

  # API Gateway REST API
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${LambdaFunctionName}-api"
      Description: API for Dog Voting App

  # API Gateway Resource (catch-all proxy)
  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: '{proxy+}'
      
  # API Gateway Resource for /api path
  ApiGatewayApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: 'api'
      
  # API Gateway Resource for /api/{proxy+}
  ApiGatewayApiProxyResource:  
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !Ref ApiGatewayApiResource
      PathPart: '{proxy+}'

  # API Gateway Method
  ApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ApiGatewayResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations"

  # API Gateway Method for root
  ApiGatewayRootMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !GetAtt ApiGateway.RootResourceId
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations"

  # API Gateway Deployment
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiGatewayMethod
      - ApiGatewayRootMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: prod

  # Lambda Permission for API Gateway
  LambdaApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/*"

Outputs:
  WebsiteURL:
    Description: URL of the Dog Voting App
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/"
    Export:
      Name: !Sub "${AWS::StackName}-WebsiteURL"

  S3BucketName:
    Description: Name of the S3 bucket for storing images
    Value: !Ref S3Bucket
    Export:
      Name: !Sub "${AWS::StackName}-S3BucketName"

  DynamoDBTableName:
    Description: Name of the DynamoDB table
    Value: !Ref DynamoDBTable
    Export:
      Name: !Sub "${AWS::StackName}-DynamoDBTableName"

  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref LambdaFunction
    Export:
      Name: !Sub "${AWS::StackName}-LambdaFunctionName" 